### ISSUE TITLE
Compilation issue in Synthesis 0.30.7

### ISSUE THREAD

**Issue by MartinHaeusler** [iAmMe27/AI-Overhaul-Patcher-Edit-by-iAmMe#1]
Hello,

there seems to be a certain incompatibility between this patcher and Synthesis 0.30.7 (potentially earlier versions as well, I've upgraded straight to this one). It says:

```
Program.cs(284,110): error CS0117: "SkyrimModHeader.HeaderFlag" does not contain a definition for "LightMaster".
```

Maybe this patcher needs an update? :)

**Comment by iAmMe27** [comment]
Just tested this on a lightly modded setup with Synthesis v0.30.7 and it completed without error:

![image](https://github.com/user-attachments/assets/abf6b010-94d4-4527-931e-6761dfc07cf6)

What is your Profile and patcher settings set to? Mine is match currently:

![image](https://github.com/user-attachments/assets/ba4aac8a-be35-425f-89e6-7a9476caeeec)

**Comment by iAmMe27** [comment]
I see the issue - newer Mutagen patchers have moved to the Starfield Small/Medium/Full terminology for ESPs. Will update the patcher to use this new terminology.

**Comment by iAmMe27** [comment]
Issue is now fixed and patcher update has been pushed. You may need to remove and re-add the patcher in the Synthesis UI.

**Comment by MartinHaeusler** [comment]
@iAmMe27 that was VERY quick, thank you :) I'll give it a try tomorrow :)

**Comment by MartinHaeusler** [comment]
@iAmMe27 sorry for the delay, busy times... It's compiling just fine now thanks!

**Comment by iAmMe27** [comment]
Glad to hear its all working now
